### PR TITLE
BLEN-54 [Community] Improve filter usd node

### PR DESCRIPTION
**Pull request by DagerD**
### PURPOSE
Add new USD node: Ignore. https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/discussions/204

### EFFECT OF CHANGE
Added new USD node: Ignore.

### TECHNICAL STEPS
Added new USD node: Ignore.

### CODE REVIEW

**Review by bnagirniak — CHANGES_REQUESTED** [review]
Discussed offline:
- Improve usage of ignore_names using patterns and use ' ' as delimiter.
- Improve FilterNode pattern to use delimiters ',' ' '

**Review by VascoPi — APPROVED** [review]
Works well.

**Review by bnagirniak — APPROVED** [review]
Tested - works well.

**Review by ARozghon — APPROVED** [review]
tested, working as expected

**Pull request merged**
