### PR TITLE
RPRBLND-1863: Merge Node not clean up Inputs.

### PR DESCRIPTION
**Pull request by DagerD**
### PURPOSE
Merge Node not clean up Inputs

### EFFECT OF CHANGE
Input sockets amount now correlates with set Inputs

### TECHNICAL STEPS
Reworked update method to make correlation work properly

### CODE REVIEW

**Review by bnagirniak — APPROVED** [review]
Tested - works good

**Review by bnagirniak — CHANGES_REQUESTED** [review]
Discussed with QA, better to do in following way: just not provide inputs_number to be less then max connected input

**Review by bnagirniak — APPROVED** [review]
Tested - works good.

**Review by VascoPi — APPROVED** [review]
Tested, works fine.

**Pull request merged**
