### PR TITLE
RPRBLND-1713: Move plugin libraries to submodules

### PR DESCRIPTION
**Pull request by bnagirniak**
### PURPOSE
Libraries USD, HdRPR, MaterialX (we can use from HdRPR submodule) would be much more useful to move them as submodules. This helps other developers to build submodules with required versions.

### TECHNICAL STEPS
1. Set USD, HdRPR as submodules in deps folder. MaterialX is submodule of HdRPR. USD repo set to 20.05 version which is currently working correctly.
2. Created tools/build.py script which builds all submodules, generates scripts, copied libs and creates zip addon. It is also available to separate each process.
3. Removed HDUSD_LIBS_DIR env variable from code usage as not needed.

### NOTES FOR REVIEWERS
Make sure that python3.9 is main system python or adjust PATH to set it.

**To build in Windows**
Open VS 2017 cmd tools and run:
\> git submodule update --init --recursive
\> python tools\build.py -all -G "Visual Studio 15 2017 Win64"

**To build in Linux**
Open terminal and run:
\> git submodule update --init --recursive
\> python tools\build.py -all

### CODE REVIEW

**Comment by ardraeiss** [comment]
Note: there should be no spaces in the full path to the project folder otherwise dependencies builder will fail on boost library building.

**Review by ardraeiss — APPROVED** [review]
OK

**Comment by bnagirniak** [comment]
Status on CIS: 
- on Windows it was successfully built
- on Linux: there are build issues during compiling USD, which we are fixing.

**Comment by bnagirniak** [comment]
Submodules were successfully built on Windows and Linux18 on CIS. This PR is ready to merge.

**Pull request merged**
