### PR TITLE
BLEN-44: PRman render delegate support

### PR DESCRIPTION
**Pull request by DagerD**
### PURPOSE
Add support for RenderMan render delegate

### EFFECT OF CHANGE
Added RenderMan render delegate

### TECHNICAL STEPS
- Added flags for build script
- UsdImagingLite fixed for correctly setting clearColor
- Added try ... except for Render method due to known RenderMan issue
- Render method in preview and final renders moved under while(true) loop
- _sync_render_settings now returns bool to indicate if it finished ok

### NOTES FOR REVIEWERS
Known issue: https://github.com/PixarAnimationStudios/USD/issues/1415
USD doesn't have implementation for RenderMan rendering progress (renderer.GetRenderStats() doesn't have 'percentDone')
Material with image as texture doesn't work (likely because RenderMan has its own nodes for this)

To make RenderMan works you need to set environment variables https://graphics.pixar.com/usd/release/plugins_renderman.html#running-hdprman

CIS:REBUILD_DEPS

### CODE REVIEW

**Review by VascoPi — APPROVED** [review]
Implementation works as intended.

**Comment by VascoPi** [comment]
If Renderman PRMANTREE is not in env variables it causes a crash while final render.

**Review by bnagirniak — APPROVED** [review]
Looks good

**Review by VascoPi — APPROVED** [review]
Works well.

**Pull request merged**
