### PR TITLE
RPRBLND-1958: Update Warning image for restart render

### PR DESCRIPTION
**Pull request by DagerD**
### PURPOSE
Update Warning image for restart render

### EFFECT OF CHANGE
Render restarts by itself without warning image if render quality changed

### TECHNICAL STEPS
Added creation of new render if render quality changed

### CODE REVIEW

**Review by bnagirniak — APPROVED** [review]
Tested - works ok

**Review by VascoPi — COMMENTED** [review]
Now in viewport render works only in Full mode, the render result of other modes looks like GL render.

**Comment by bsavery** [comment]
> Now in viewport render works only in Full mode, the render result of other modes looks like GL render.

I'm not sure if this is an issue?? Do you approve or not?

**Review by bnagirniak — APPROVED** [review]
Did fix of restart render. Now it works correct.

**Comment by VascoPi** [comment]
> > Now in viewport render works only in Full mode, the render result of other modes looks like GL render.
> 
> I'm not sure if this is an issue?? Do you approve or not?

Discussed an issue offline.
Now works as expected.

**Review by VascoPi — APPROVED** [review]
Tested, works well.

**Pull request merged**
