### PR TITLE
RPRBLND-2042: Update HdRPR with Core 2.2.10.

### PR DESCRIPTION
**Pull request by bnagirniak**
### PURPOSE
RPR Core to 2.2.10 is available.

### EFFECT OF CHANGE
Updated RPR Core to 2.2.10.

### TECHNICAL STEPS
Updated HdRPR submodule to branch with Core 2.2.10.
Improved build script.

### NOTES FOR REVIEWERS
Waiting for https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/515 be merged.

CIS:REBUILD_DEPS

### CODE REVIEW

**Comment by bnagirniak** [comment]
This PR doesn't work as expected because we aren't use USD schema described in https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/508
Therefore I'm closing this PR and created another one with RPR Core 2.2.10 #169 which doesn't use USD schema.

**Comment by bnagirniak** [comment]
Made adjustments in SetRendererSetting() with new keys for HdRPR, therefore reopening this PR and closing #169

**Comment by bnagirniak** [comment]
Moving to draft because waiting for fixed in HybridPro

**Review by DagerD — APPROVED** [review]

**Comment by bnagirniak** [comment]
Good, ready to merge

**Pull request merged**
