### PR TITLE
RPRBLND-2021: Bug in PreviewEngine

### PR DESCRIPTION
**Pull request by DagerD**
### PURPOSE
Fix bug in PreviewEngine.

### EFFECT OF CHANGE
No more error in console while stretching panel with preview.

### TECHNICAL STEPS
Added check for prim validity

### CODE REVIEW

**Review by bnagirniak — APPROVED** [review]
Looks good

**Review by VascoPi — APPROVED** [review]
Works well. Tested.

**Review by bnagirniak — CHANGES_REQUESTED** [review]
Discussed offline, Better to do this using is_synced like we did in RPR plugin for PreviewEngine

**Review by bnagirniak — APPROVED** [review]
Tested - works good.

**Pull request merged**
